import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) {
      if (name === "target") continue;
      walk(path, out);
    } else if (name.endsWith(".rs")) out.push(path);
  }
  return out;
}

const rows = [];
for (const file of walk(join("src-tauri", "src"))) {
  const lines = readFileSync(file, "utf8").split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    // `#[command]` is the aliased form (`use tauri::command`), used by gogdl.
    if (!/^\s*#\[(tauri::)?command\]/.test(lines[i])) continue;
    const next = lines.slice(i + 1, i + 6).join(" ");
    const match = next.match(/\bfn\s+([A-Za-z0-9_]+)/);
    if (!match) continue;
    const rust = match[1];
    const js = rust.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
    rows.push({ rust, js, file: relative(".", file).replaceAll("\\", "/") });
  }
}
rows.sort((a, b) => a.rust.localeCompare(b.rust));

const body = [
  "# IPC index",
  "",
  "Generated by `node scripts/ipc-index.mjs`. One command per line so a search lands on the file.",
  "JS calls `invoke(\"<rust name>\", { camelCase })`. The object key drops underscores and capitalizes the next letter (`app_name` -> `appName`).",
  "",
  "| Rust command | JS wrapper shape | File |",
  "|---|---|---|",
  ...rows.map((row) => `| \`${row.rust}\` | \`${row.js}({ ... })\` | \`${row.file}\` |`),
  "",
].join("\n");

writeFileSync(join("docs", "agent", "ipc-index.md"), body);
console.log(`${rows.length} commands`);
